---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: compose-example
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: compose-example
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-alpine
        imagePullPolicy: Never
        readinessProbe:
          timeoutSeconds: 30
          exec:
            command:
             - rabbitmq-diagnostics
             - check_port_connectivity
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        # env:
        # - name: RABBITMQ_DEFAULT_USER
        #  value: "guest"
        # - name: RABBITMQ_DEFAULT_PASS
        #   value: "guest"
        # volumeMounts:
        # - name: rabbitlib
        #   mountPath: "/var/lib/rabbitmq/"
      # volumes:
      # - name: rabbitlib
      #   emptyDir: {}
---